# Generated by Django 2.2.3 on 2019-08-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(max_length=1)),
                ('doj', models.DateField()),
            ],
        ),
    ]
