# Generated by Django 2.2.5 on 2019-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('accno', models.IntegerField(max_length=99999, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('balance', models.IntegerField(max_length=9999999999)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
