# Generated by Django 2.2.3 on 2019-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(max_length=30)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doj', models.DateField()),
            ],
        ),
    ]
