# Generated by Django 2.2.5 on 2019-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cno', models.IntegerField(max_length=9999999999)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.IntegerField(max_length=8)),
            ],
        ),
    ]
